name: Automatic Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (v16)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Bump version and update README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Bump the package version
        NEW_VERSION=$(npm version patch -m "Bump version to %s [skip ci]")
        
        # Make the new version available to subsequent steps
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        
        # Extract the commit message of the latest commit
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        
        # Update README.md with the new version and commit message
        echo "Latest Version: $NEW_VERSION" >> README.md
        echo "Latest Commit: $COMMIT_MESSAGE" >> README.md
        
        # Commit and push the changes
        git add README.md package.json package-lock.json
        git commit -m "Bump version to $NEW_VERSION and update README.md [skip ci]"
        git push --follow-tags

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: Release ${{ env.NEW_VERSION }}
        draft: false
        prerelease: false
      continue-on-error: true  # continue the workflow even if this step fails

