name: Automatic README and Version Update

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (v16)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Bump version and update README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Bump the package version
        NEW_VERSION=$(npm version patch -m "Bump version to %s [skip ci]")
        
        # Extract the commit message of the latest commit
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        
        # Update Change Log in README.md with the new version and commit message
        echo -e "### $NEW_VERSION\n\n- $COMMIT_MESSAGE\n\n$(cat README.md)" > README.md

        # Update the Version in README.md
        sed -i "s/Version: [0-9]\+\.[0-9]\+\.[0-9]\+/Version: $NEW_VERSION/" README.md

        # Commit and push the changes
        git add README.md
        git commit -m "Update README.md with latest version and change log [skip ci]"
        git push

