name: Automatic README and Version Update

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (v16)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Bump version and update README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Bump the package version
        NEW_VERSION=$(npm version patch -m "Bump version to %s [skip ci]")
        
        # Extract the commit message of the latest commit
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        
        # Update the Version field in README.md
        sed -i "s/__Version__:.*/__Version__: $NEW_VERSION/" README.md

        # Add new change log entry to README.md
        awk -v version="$NEW_VERSION" -v message="$COMMIT_MESSAGE" '/## Change Log/{print; print "### " version "\n\n- " message "\n"; next}1' README.md > README.tmp && mv README.tmp README.md
        
        # Commit and push the changes
        git add README.md
        git commit -m "Update README.md with latest version and change log [skip ci]"
        git push

